// Stalwork Command Center — Demo Data
// All names, projects, and roles are real Stalwork team members.

export const users = [
  {
    id: "ben",
    name: "Ben Kulick",
    role: "admin",
    title: "Owner & Admin",
    icon: "shield",
    description: "Full platform access — all projects, all reports, all settings.",
  },
  {
    id: "james",
    name: "James Todd",
    role: "pm",
    title: "Project Manager",
    icon: "clipboard",
    description: "Project dashboards, daily logs, crew scheduling, and client reports.",
  },
  {
    id: "laura",
    name: "Laura W.",
    role: "client",
    title: "Homeowner, Winkenbach Residence",
    icon: "home",
    description: "Client portal — project timeline, progress photos, and weekly updates.",
  },
  {
    id: "aaron",
    name: "Aaron Grimes",
    role: "field",
    title: "Framing Superintendent",
    icon: "hardhat",
    description: "Daily log entry, crew check-in, and task updates from the field.",
  },
];

export const projects = [
  {
    id: "winkenbach",
    name: "Winkenbach Residence",
    location: "San Luis Obispo, CA",
    client: "Laura W.",
    clientEmail: "laura.w@email.com",
    pm: "James Todd",
    status: "active",
    startDate: "2025-06-15",
    estimatedCompletion: "2026-04-30",
    budget: 1850000,
    spent: 1120000,
    percentComplete: 62,
    currentPhase: "Interior Finishes",
    phases: [
      { name: "Site Prep & Grading", status: "complete", percent: 100 },
      { name: "Foundation & Concrete", status: "complete", percent: 100 },
      { name: "Framing", status: "complete", percent: 100 },
      { name: "Roofing", status: "complete", percent: 100 },
      { name: "Plumbing Rough-In", status: "complete", percent: 100 },
      { name: "Electrical Rough-In", status: "complete", percent: 100 },
      { name: "HVAC", status: "complete", percent: 100 },
      { name: "Insulation & Drywall", status: "complete", percent: 100 },
      { name: "Interior Finishes", status: "in-progress", percent: 45 },
      { name: "Tile & Stone", status: "upcoming", percent: 0 },
      { name: "Finish Carpentry", status: "upcoming", percent: 0 },
      { name: "Landscape", status: "upcoming", percent: 0 },
      { name: "Final Punch & Closeout", status: "upcoming", percent: 0 },
    ],
  },
  {
    id: "hope",
    name: "Hope Residence",
    location: "Paso Robles, CA",
    client: "Michael & Sarah H.",
    clientEmail: "hope.family@email.com",
    pm: "Ben Kulick",
    status: "active",
    startDate: "2025-09-01",
    estimatedCompletion: "2026-08-15",
    budget: 2200000,
    spent: 640000,
    percentComplete: 35,
    currentPhase: "Framing",
    phases: [
      { name: "Site Prep & Grading", status: "complete", percent: 100 },
      { name: "Foundation & Concrete", status: "complete", percent: 100 },
      { name: "Framing", status: "in-progress", percent: 60 },
      { name: "Roofing", status: "upcoming", percent: 0 },
      { name: "Plumbing Rough-In", status: "upcoming", percent: 0 },
      { name: "Electrical Rough-In", status: "upcoming", percent: 0 },
      { name: "HVAC", status: "upcoming", percent: 0 },
      { name: "Insulation & Drywall", status: "upcoming", percent: 0 },
      { name: "Interior Finishes", status: "upcoming", percent: 0 },
      { name: "Tile & Stone", status: "upcoming", percent: 0 },
      { name: "Finish Carpentry", status: "upcoming", percent: 0 },
      { name: "Landscape", status: "upcoming", percent: 0 },
      { name: "Final Punch & Closeout", status: "upcoming", percent: 0 },
    ],
  },
  {
    id: "athanasakos",
    name: "Athanasakos Residence",
    location: "Arroyo Grande, CA",
    client: "George & Elena A.",
    clientEmail: "athanasakos@email.com",
    pm: "Frank Perea",
    status: "active",
    startDate: "2025-11-01",
    estimatedCompletion: "2026-10-30",
    budget: 1650000,
    spent: 280000,
    percentComplete: 18,
    currentPhase: "Foundation & Concrete",
    phases: [
      { name: "Site Prep & Grading", status: "complete", percent: 100 },
      { name: "Foundation & Concrete", status: "in-progress", percent: 70 },
      { name: "Framing", status: "upcoming", percent: 0 },
      { name: "Roofing", status: "upcoming", percent: 0 },
      { name: "Plumbing Rough-In", status: "upcoming", percent: 0 },
      { name: "Electrical Rough-In", status: "upcoming", percent: 0 },
      { name: "HVAC", status: "upcoming", percent: 0 },
      { name: "Insulation & Drywall", status: "upcoming", percent: 0 },
      { name: "Interior Finishes", status: "upcoming", percent: 0 },
      { name: "Tile & Stone", status: "upcoming", percent: 0 },
      { name: "Finish Carpentry", status: "upcoming", percent: 0 },
      { name: "Landscape", status: "upcoming", percent: 0 },
      { name: "Final Punch & Closeout", status: "upcoming", percent: 0 },
    ],
  },
  {
    id: "okimoto",
    name: "Okimoto Residence",
    location: "San Luis Obispo, CA",
    client: "David & Karen O.",
    clientEmail: "okimoto@email.com",
    pm: "James Todd",
    status: "active",
    startDate: "2025-04-01",
    estimatedCompletion: "2026-02-28",
    budget: 1400000,
    spent: 1180000,
    percentComplete: 85,
    currentPhase: "Landscape",
    phases: [
      { name: "Site Prep & Grading", status: "complete", percent: 100 },
      { name: "Foundation & Concrete", status: "complete", percent: 100 },
      { name: "Framing", status: "complete", percent: 100 },
      { name: "Roofing", status: "complete", percent: 100 },
      { name: "Plumbing Rough-In", status: "complete", percent: 100 },
      { name: "Electrical Rough-In", status: "complete", percent: 100 },
      { name: "HVAC", status: "complete", percent: 100 },
      { name: "Insulation & Drywall", status: "complete", percent: 100 },
      { name: "Interior Finishes", status: "complete", percent: 100 },
      { name: "Tile & Stone", status: "complete", percent: 100 },
      { name: "Finish Carpentry", status: "complete", percent: 100 },
      { name: "Landscape", status: "in-progress", percent: 40 },
      { name: "Final Punch & Closeout", status: "upcoming", percent: 0 },
    ],
  },
];

export const crews = [
  { id: "concrete", name: "Pablo Valencia", role: "Concrete Super", specialty: "Concrete", currentProject: "athanasakos" },
  { id: "framing", name: "Aaron Grimes", role: "Superintendent", specialty: "General", currentProject: "winkenbach" },
  { id: "tile", name: "Omar Torres", role: "Tile Super", specialty: "Tile & Stone", currentProject: null },
  { id: "landscape", name: "Tricia Rohr", role: "Landscape Director", specialty: "Landscape", currentProject: "okimoto" },
  { id: "finish1", name: "Gennady Fedonenko", role: "Finish Carpenter", specialty: "Finish Carpentry", currentProject: "winkenbach" },
  { id: "finish2", name: "Miguel Contreras", role: "Finish Carpenter", specialty: "Finish Carpentry", currentProject: "winkenbach" },
  { id: "foreman1", name: "Lalo Hernandez", role: "Foreman", specialty: "General", currentProject: "hope" },
  { id: "foreman2", name: "Dylan Baca", role: "Framing Foreman", specialty: "Framing", currentProject: "hope" },
];

export const dailyLogs = [
  {
    id: 1,
    projectId: "winkenbach",
    date: "2026-02-13",
    author: "James Todd",
    weather: "Sunny, 62°F",
    crewOnSite: ["Gennady Fedonenko", "Miguel Contreras"],
    workCompleted: "Continued interior door installation in master suite. Hung 4 doors, trimmed 2. Custom closet millwork delivered and staged in garage.",
    issues: "None",
    photos: 2,
  },
  {
    id: 2,
    projectId: "winkenbach",
    date: "2026-02-12",
    author: "James Todd",
    weather: "Overcast, 58°F",
    crewOnSite: ["Gennady Fedonenko", "Miguel Contreras"],
    workCompleted: "Kitchen cabinet installation 90% complete. Island countertop template taken by stone fabricator. Scheduled installation for 2/19.",
    issues: "Stone fabricator pushed backsplash install to 2/24 — waiting on material from supplier.",
    photos: 1,
  },
  {
    id: 3,
    projectId: "hope",
    date: "2026-02-13",
    author: "Aaron Grimes",
    weather: "Clear, 55°F",
    crewOnSite: ["Aaron Grimes", "Dylan Baca", "Lalo Hernandez"],
    workCompleted: "Second floor framing continues. East wall raised and braced. Window headers set for great room. Roof truss delivery confirmed for Monday 2/17.",
    issues: "None",
    photos: 2,
  },
  {
    id: 4,
    projectId: "athanasakos",
    date: "2026-02-13",
    author: "Frank Perea",
    weather: "Partly cloudy, 60°F",
    crewOnSite: ["Pablo Valencia"],
    workCompleted: "Foundation stem walls poured — north and east sides. Forms to be stripped Friday 2/14. Anchor bolt survey scheduled for 2/17.",
    issues: "Minor rebar spacing adjustment needed on south wall per engineer's note. Corrected on site.",
    photos: 1,
  },
  {
    id: 5,
    projectId: "okimoto",
    date: "2026-02-13",
    author: "Tricia Rohr",
    weather: "Sunny, 64°F",
    crewOnSite: ["Tricia Rohr"],
    workCompleted: "Specimen olive trees delivered and placed. Irrigation trenching for front yard 60% complete. Drought-tolerant planting beds prepped along south fence.",
    issues: "Waiting on final hardscape material delivery — cobblestone pavers ETA 2/18.",
    photos: 1,
  },
];

export const changeOrders = [
  {
    id: 1,
    projectId: "winkenbach",
    title: "Upgrade master bath tile to Calacatta marble",
    description: "Client requested upgrade from porcelain to natural Calacatta marble for master bathroom floor and shower walls.",
    requestedBy: "Laura W.",
    date: "2026-01-15",
    estimatedCost: 18500,
    status: "approved",
    approvedDate: "2026-01-20",
  },
  {
    id: 2,
    projectId: "hope",
    title: "Add wine cellar under staircase",
    description: "Owners want to convert under-stair storage to a climate-controlled wine cellar. Requires additional electrical, insulation, and custom door.",
    requestedBy: "Michael H.",
    date: "2026-02-05",
    estimatedCost: 34000,
    status: "pending",
    approvedDate: null,
  },
  {
    id: 3,
    projectId: "winkenbach",
    title: "Extend covered patio by 8 feet",
    description: "Extend rear covered patio to accommodate larger outdoor dining area. Requires additional concrete, framing, and roofing.",
    requestedBy: "Laura W.",
    date: "2025-11-28",
    estimatedCost: 22000,
    status: "approved",
    approvedDate: "2025-12-05",
  },
];

export const weeklyReports = [
  {
    id: 1,
    projectId: "winkenbach",
    weekEnding: "2026-02-14",
    summary: "Good progress this week on interior finishes. Kitchen cabinetry is nearly complete and the stone fabricator has templated for countertops — installation is scheduled for February 19th. Your custom interior doors are being hung in the master suite, with 4 of 8 doors completed. The closet millwork has been delivered and will be installed next week. One note: the backsplash tile installation has shifted to February 24th due to a material delay from the supplier. This does not affect the overall project timeline.",
    nextWeek: "Countertop installation, continued door hanging and trim work, closet millwork installation begins, and paint touch-ups in completed rooms.",
    budgetNote: "The approved Calacatta marble upgrade ($18,500) has been factored into the running total. Current spend is tracking within 2% of the adjusted budget.",
  },
];

export const projectPhotos = [
  { id: 1, projectId: "winkenbach", label: "Kitchen cabinet installation", date: "2026-02-13", phase: "Interior Finishes", h: 300, url: "https://images.unsplash.com/photo-1591825381767-c7137b8eda0f?w=600&fit=crop" },
  { id: 2, projectId: "winkenbach", label: "Master suite door installation", date: "2026-02-13", phase: "Interior Finishes", h: 250, url: "https://images.unsplash.com/photo-1735919319641-816e30d3a3d8?w=600&fit=crop" },
  { id: 3, projectId: "winkenbach", label: "Stone countertop template", date: "2026-02-12", phase: "Interior Finishes", h: 320, url: "https://images.unsplash.com/photo-1687942918532-69295473701d?w=600&fit=crop" },
  { id: 4, projectId: "winkenbach", label: "Custom millwork delivery", date: "2026-02-12", phase: "Interior Finishes", h: 270, url: "https://images.unsplash.com/photo-1683115096447-5d01c11d3ead?w=600&fit=crop" },
  { id: 5, projectId: "winkenbach", label: "Insulation complete — living room", date: "2026-01-20", phase: "Insulation & Drywall", h: 300, url: "https://images.unsplash.com/photo-1768321902841-aafb906dc0a4?w=600&fit=crop" },
  { id: 6, projectId: "winkenbach", label: "Drywall finishing", date: "2026-01-18", phase: "Insulation & Drywall", h: 260, url: "https://images.unsplash.com/photo-1766961980272-921bba4240bc?w=600&fit=crop" },
  { id: 7, projectId: "winkenbach", label: "HVAC ductwork installation", date: "2026-01-08", phase: "HVAC", h: 300, url: "https://images.unsplash.com/photo-1558358235-a0a93f68a52c?w=600&fit=crop" },
  { id: 8, projectId: "winkenbach", label: "Electrical rough-in inspection", date: "2025-12-18", phase: "Electrical Rough-In", h: 280, url: "https://images.unsplash.com/photo-1767514536570-83d70c024247?w=600&fit=crop" },
  { id: 9, projectId: "winkenbach", label: "Plumbing rough-in complete", date: "2025-12-01", phase: "Plumbing Rough-In", h: 310, url: "https://images.unsplash.com/photo-1694827893591-af9b80361599?w=600&fit=crop" },
  { id: 10, projectId: "winkenbach", label: "Roof sheathing and waterproofing", date: "2025-11-15", phase: "Roofing", h: 260, url: "https://images.unsplash.com/photo-1760331840361-d751cfc1becf?w=600&fit=crop" },
  { id: 11, projectId: "winkenbach", label: "Framing complete — aerial view", date: "2025-10-15", phase: "Framing", h: 300, url: "https://images.unsplash.com/photo-1750500383359-c8a5107bf946?w=600&fit=crop" },
  { id: 12, projectId: "winkenbach", label: "Foundation pour — north wing", date: "2025-08-20", phase: "Foundation & Concrete", h: 280, url: "https://images.unsplash.com/photo-1764856601179-dfeca7b37e4c?w=600&fit=crop" },
  { id: 13, projectId: "winkenbach", label: "Site grading and preparation", date: "2025-07-01", phase: "Site Prep & Grading", h: 260, url: "https://images.unsplash.com/photo-1701656625693-35e1fd3614e1?w=600&fit=crop" },
];
